# 개발용 도커 설정
version: '3.9'

networks:
  projectname:

volumes:
  projectname-db:

services:
  db:
    image: postgres:14-alpine
    networks:
      - projectname
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - "projectname-db:/var/lib/postgresql/data"
    environment:
      LANG: C.utf8
      TZ: "Asia/Seoul"
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
