name: Kotlin

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**/*.kt"
      - "**/*.kts"
      - ".github/workflows/kotlin.yml"
  pull_request:
    paths:
      - "**/*.kt"
      - "**/*.kts"
      - ".github/workflows/kotlin.yml"

jobs:
  build:
    name: "ğŸ—ï¸ Build code"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ github.run_id }}
          path: |
            build/**
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - name: Build with Gradle
        run: gradle build
  test:
    name: "âœ… Test code"
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ github.run_id }}
          path: |
            build/**
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - name: Test running
        run: gradle test
  qodana:
    name: "ğŸ” Scan code"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JetBrains/qodana-action@v4.1.1
        with:
          linter: jetbrains/qodana-jvm
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
